CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(50),
  login varchar(25) NOT NULL,
  name varchar(25),
  birthday timestamp
);

CREATE TABLE IF NOT EXISTS films (
  film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50),
  description varchar(200),
  release_date timestamp,
  duration integer,
  rate integer,
  raiting varchar(5)
);

CREATE TABLE IF NOT EXISTS friends (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  friend_id integer NOT NULL,
  status varchar,
  status_start timestamp,
  status_end timestamp
);

CREATE TABLE IF NOT EXISTS filmGenres (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  genre_id integer NOT NULL,
  status varchar,
  status_start timestamp,
  status_end timestamp
);

CREATE TABLE IF NOT EXISTS genres (
  genre_id integer NOT NULL PRIMARY KEY,
  film_id integer NOT NULL,
  genre_name varchar(8)
);

CREATE TABLE IF NOT EXISTS likes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  status varchar,
  status_start timestamp,
  status_end timestamp
);